name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run tests (optional)
      - name: Run tests
        run: flutter test || echo "No tests found"

      # 5. Build APK
      - name: Build APK
        run: flutter build apk --release
