name: "Build & Release for Android"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release for Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java Environment
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Setup Flutter Environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          architecture: x64

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # Step 6: Debug APK Path
      - name: Debug APK Path
        run: |
          ls build/app/outputs/flutter-apk/

      # Step 7: Upload APK to GitHub Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-*-release.apk"
          tag: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          token: ${{ secrets.TOKEN }}
