name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # 3. Debug Flutter Installation
      - name: Debug Flutter
        run: flutter --version

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Run tests
      - name: Run tests
        run: flutter test
