name: Flutter CI/CD on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Flutter on Windows
      - name: Setup Flutter on Windows
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run tests
      - name: Run tests
        run: flutter test

      # 5. Build APK
      - name: Build APK
        run: flutter build apk --release
