name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run tests
      - name: Run tests
        run: flutter test

      # 5. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 6. Build iOS (Optional, macOS environment required)
      # Uncomment this section if building for iOS.
      # - name: Build iOS
      #   run: flutter build ios --release
      #   if: runner.os == 'macOS'

      # 7. Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
